### ISSUE TITLE
back4app搭建好日志没有日志显示，查看不到密码

### ISSUE THREAD

**Issue by plcxg** [wy580477/Alist-on-PaaS#2]
![部署](https://user-images.githubusercontent.com/127076266/229667670-a28178fa-9a85-4dae-8326-09976ec3cde9.png)
![log](https://user-images.githubusercontent.com/127076266/229667675-5fa7d225-3e31-41f6-a487-12f5f623f6d7.png)

**Comment by wy580477** [comment]
应该是 back4app 的问题了，我试了简单部署一个 nginx 镜像，也没有日志。

**Comment by plcxg** [comment]
好的，谢谢
