### ISSUE TITLE
Patr运行报错

### ISSUE THREAD

**Issue by Mhatetk** [wy580477/Alist-on-PaaS#5]
Patr在START时报错:
An internal server error has occured. Please try again later

**Comment by wy580477** [comment]
发一下 patr 容器面板的日志

**Comment by Mhatetk** [comment]
![image](https://github.com/wy580477/Alist-on-PaaS/assets/119028658/81707092-91f1-4369-ac5a-35e251832d9c)

**Comment by Mhatetk** [comment]
> 发一下 patr 容器面板的日志

上面发了

**Comment by wy580477** [comment]
log 都加载不出来，我觉得是 Patr 平台自身出问题了，这平台就是容易坏的。 ╮(′～‵〞)╭

**Comment by Mhatetk** [comment]
> log 都加载不出来，我觉得是 Patr 平台自身出问题了，这平台就是容易坏的。 ╮(′～‵〞)╭

好吧,我过几天再试试
